---
- name: Common setup for all servers
  hosts: master
  become: true
  tasks:
    - name: Create resolved.conf.d directory if not exists
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory

    - name: Create dns_servers.conf file if not exists
      file:
        path: /etc/systemd/resolved.conf.d/dns_servers.conf
        state: touch

    - name: Set DNS servers in resolved.conf
      blockinfile:
        path: /etc/systemd/resolved.conf.d/dns_servers.conf
        block: |
          [Resolve]
          DNS=${DNS_SERVERS}

    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted

    - name: Disable swap
      command: swapoff -a

    - name: Persist swap-off across reboot
      cron:
        name: Disable Swap
        job: "/sbin/swapoff -a"
        user: root
        cron_file: swapoff_a
        state: present
