apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginxdeployment.fullname" . }}
  labels:
    {{- include "nginxdeployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "nginxdeployment.selectorLabels" . | nindent 4 }}
